Make CLOCK_MONOTONIC_PRECISE reachable on FreeBSD
On FreeBSD, the build breaks with the following error: use of undeclared identifier 'CLOCK_MONOTONIC_PRECISE'.
This happens, because CLOCK_MONOTONIC_PRECISE from time.h is not visible on FreeBSD, if _POSIX_C_SOURCE=200112L is defined (Issue #33).
The patch makes it visible the hard way ;)